### ISSUE TITLE
resolution select

### ISSUE THREAD

**Issue by HariC137** [jtara1/horriblesubs_batch_downloader#11]
give an option to select resolution this takes the magnet links of the highest resolution and individual episodes

**Comment by AliMZaini** [comment]
> give an option to select resolution this takes the magnet links of the highest resolution and individual episodes

Here is a similar application which allows you to select the quality and range of episodes you want to download and includes float episode numbers: https://github.com/AliMZaini/horriblesubsscraper

**Comment by AlexMusabelliu** [comment]
in the pull requests, i put an updated ver. with this feature

**Comment by jtara1** [comment]
should be implemented in #15 thanks to @AlexMusabelliu

You should be able to select a resolution with a matching index and `--quality <index>` option, and I think they usually upload [480p, 720p, 1080p]
