### ISSUE TITLE
Support for float episode numbers

### ISSUE THREAD

**Issue by shimmy568** [jtara1/horriblesubs_batch_downloader#12]
Cant download https://horriblesubs.info/shows/sword-art-online-alicization/ since it has episode 18.5 and that messes up on an int() call

**Comment by AliMZaini** [comment]
> Cant download https://horriblesubs.info/shows/sword-art-online-alicization/ since it has episode 18.5 and that messes up on an int() call

Here is a similar application which allows you to select the quality and range of episodes you want to download and includes float episode numbers: https://github.com/AliMZaini/horriblesubsscraper

**Comment by AlexMusabelliu** [comment]
in the pull requests, i put an updated ver. with this feature

**Comment by jtara1** [comment]
should be implemented in #15 thanks to @AlexMusabelliu

tested this with '91 Days' show and wrote a few unit tests for it in `test/`
