### ISSUE TITLE
Search Error?

### ISSUE THREAD

**Issue by Oliyy** [jtara1/horriblesubs_batch_downloader#8]
Am I doing something wrong, the minimal
<img width="692" alt="screen shot 2018-08-12 at 22 07 18" src="https://user-images.githubusercontent.com/13434616/44013802-b949d22a-9e7c-11e8-8122-ea2da3796e0b.png">
 documentation has got me quite confused

**Comment by jtara1** [comment]
There were lots of updates needed for changes to html that was parsed. Should be fixed since 0.2.6 release. Focused only on supporting python 3 at this point.

try

`pip3 install -U horriblesubs-batch-downloader --user`

then `hsbd jojo` again

**Comment by jtara1** [comment]
@Oliyy can you confirm this fixed it?

**Comment by Oliyy** [comment]
I can try it out later.
